[dependencies]
nixPkgs = ["bun", "boost183"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bash -lc 'export LD_LIBRARY_PATH=$(dirname $(readlink -f $(which innoextract)))/../lib:${LD_LIBRARY_PATH}:/nix/store/boost-1.83.0/lib; exec ./server"